from services.analysis.models import AnalysisResult
from ui.foundation.models import GuiMetric, GuiSection


class AnalysisPresenter:
    """
    Builds display-only analysis dashboard sections for the GUI.

    The presenter consumes deterministic AnalysisResult objects and projects
    them into stable GUI sections. It never calculates indicators, interprets
    candles, generates signals or makes trading decisions.
    """

    def create_sections(self, analysis_result: AnalysisResult) -> list[GuiSection]:
        sections = [
            self._create_summary_section(analysis_result),
            self._create_score_section(analysis_result),
        ]

        notes = self._create_notes_section(analysis_result)
        if notes is not None:
            sections.append(notes)

        return sections

    def _create_summary_section(self, analysis_result: AnalysisResult) -> GuiSection:
        return GuiSection(
            title="Analysis Dashboard",
            description="High-level deterministic output from the Analysis Layer.",
            metrics=[
                GuiMetric("Symbol", analysis_result.symbol.upper() or "N/A"),
                GuiMetric("Overall Score", str(analysis_result.overall_score)),
            ],
        )

    def _create_score_section(self, analysis_result: AnalysisResult) -> GuiSection:
        return GuiSection(
            title="Analysis Scores",
            description="Technical scores calculated before the GUI receives the result.",
            metrics=[
                GuiMetric("Trend Score", str(analysis_result.trend_score)),
                GuiMetric("Momentum Score", str(analysis_result.momentum_score)),
                GuiMetric("Volatility Score", str(analysis_result.volatility_score)),
                GuiMetric("Structure Score", str(analysis_result.structure_score)),
                GuiMetric("Volume Score", str(analysis_result.volume_score)),
                GuiMetric("Market Regime Score", str(analysis_result.market_regime_score)),
                GuiMetric("Relative Strength Score", str(analysis_result.relative_strength_score)),
                GuiMetric("Candlestick Score", str(analysis_result.candlestick_score)),
            ],
        )

    def _create_notes_section(self, analysis_result: AnalysisResult) -> GuiSection | None:
        if not analysis_result.notes:
            return None

        return GuiSection(
            title="Analysis Notes",
            description="Deterministic notes generated by the Analysis Layer.",
            metrics=[
                GuiMetric(f"Note {index}", note)
                for index, note in enumerate(analysis_result.notes, start=1)
            ],
        )
