from services.backtesting.models import BacktestResult
from ui.foundation.models import GuiMetric, GuiSection


class BacktestingPresenter:
    """
    Builds display-only backtesting dashboard sections for the GUI.

    The presenter consumes a completed BacktestResult from the deterministic
    Backtesting Engine and projects it into stable GUI sections. It never
    simulates trades, recalculates performance, creates trade plans or makes
    trading decisions.
    """

    def create_sections(self, result: BacktestResult) -> list[GuiSection]:
        sections = [
            self._create_summary_section(result),
            self._create_trade_statistics_section(result),
            self._create_trade_log_section(result),
        ]

        diagnostics = self._create_diagnostics_section(result)
        if diagnostics is not None:
            sections.append(diagnostics)

        return sections

    def _create_summary_section(self, result: BacktestResult) -> GuiSection:
        return GuiSection(
            title="Backtesting Dashboard",
            description="High-level result from the deterministic Backtesting Engine.",
            metrics=[
                GuiMetric("Symbol", result.symbol or "N/A"),
                GuiMetric("Valid Backtest", self._format_bool(result.valid_backtest)),
                GuiMetric("Total Trades", str(result.total_trades)),
                GuiMetric("Total Gross P/L", f"{result.total_gross_pnl:.2f}"),
                GuiMetric("Total Return", f"{result.total_return_pct:.2f}%"),
            ],
        )

    def _create_trade_statistics_section(self, result: BacktestResult) -> GuiSection:
        return GuiSection(
            title="Backtest Trade Statistics",
            description="Trade statistics calculated before the GUI receives the result.",
            metrics=[
                GuiMetric("Winning Trades", str(result.winning_trades)),
                GuiMetric("Losing Trades", str(result.losing_trades)),
                GuiMetric("Win Rate", f"{result.win_rate:.2f}%"),
                GuiMetric("Max Drawdown", f"{result.max_drawdown:.2f}%"),
            ],
        )

    def _create_trade_log_section(self, result: BacktestResult) -> GuiSection:
        if not result.trades:
            metrics = [GuiMetric("Trades", "None")]
        else:
            metrics = []
            for index, trade in enumerate(result.trades, start=1):
                metrics.append(
                    GuiMetric(
                        f"Trade {index}",
                        self._format_trade(trade),
                        helper_text=f"Exit reason: {trade.exit_reason}",
                    )
                )

        return GuiSection(
            title="Backtest Trade Log",
            description="Display-only list of simulated trades generated by the Backtesting Engine.",
            metrics=metrics,
        )

    def _create_diagnostics_section(self, result: BacktestResult) -> GuiSection | None:
        diagnostics: list[GuiMetric] = []

        for index, warning in enumerate(result.warnings, start=1):
            diagnostics.append(GuiMetric(f"Warning {index}", warning))

        for index, reason in enumerate(result.reasons, start=1):
            diagnostics.append(GuiMetric(f"Reason {index}", reason))

        if not diagnostics:
            return None

        return GuiSection(
            title="Backtesting Diagnostics",
            description="Deterministic warnings and reasons from the Backtesting Engine.",
            metrics=diagnostics,
        )

    def _format_trade(self, trade) -> str:
        return (
            f"{trade.symbol} {trade.action} | "
            f"{trade.shares} shares | "
            f"{trade.entry_price:.2f} → {trade.exit_price:.2f} | "
            f"P/L {trade.gross_pnl:.2f} | "
            f"Return {trade.return_pct:.2f}%"
        )

    def _format_bool(self, value: bool) -> str:
        return "Yes" if value else "No"
