from services.ai.models import AIExplanationResult
from ui.foundation.models import GuiMetric, GuiSection


class ExplanationPresenter:
    """
    Builds display-only GUI sections from AIExplanationResult.

    This presenter does not call AI providers, does not calculate trading logic
    and does not alter deterministic Orion results. It only projects existing
    explanation output into GUI-ready sections.
    """

    def create_sections(self, result: AIExplanationResult) -> list[GuiSection]:
        sections: list[GuiSection] = [self._create_summary_section(result)]

        for explanation_section in result.sections:
            sections.append(
                GuiSection(
                    title=explanation_section.title,
                    description="Deterministic explanation section.",
                    metrics=[
                        GuiMetric(
                            label=f"Bullet {index}",
                            value=bullet,
                        )
                        for index, bullet in enumerate(explanation_section.bullets, start=1)
                    ],
                )
            )

        if result.reasons:
            sections.append(
                GuiSection(
                    title="Explanation Sources",
                    description="Why this explanation is valid.",
                    metrics=[
                        GuiMetric(label=f"Reason {index}", value=reason)
                        for index, reason in enumerate(result.reasons, start=1)
                    ],
                )
            )

        if result.warnings:
            sections.append(
                GuiSection(
                    title="Explanation Warnings",
                    description="Warnings generated by deterministic explanation validation.",
                    metrics=[
                        GuiMetric(label=f"Warning {index}", value=warning)
                        for index, warning in enumerate(result.warnings, start=1)
                    ],
                )
            )

        return sections

    def _create_summary_section(self, result: AIExplanationResult) -> GuiSection:
        status = "Valid" if result.valid_explanation else "Invalid"
        return GuiSection(
            title="AI Explanation Summary",
            description="Display-only explanation generated from deterministic Orion output.",
            metrics=[
                GuiMetric("Symbol", result.symbol or "UNKNOWN"),
                GuiMetric("Status", status),
                GuiMetric("Source Count", str(result.source_count)),
                GuiMetric("Summary", result.summary or "No explanation summary available."),
            ],
        )
