from services.signals.models import SignalResult
from ui.foundation.models import GuiMetric, GuiSection


class SignalPresenter:
    """
    Builds display-only signal dashboard sections for the GUI.

    The presenter consumes deterministic SignalResult objects and projects them
    into stable GUI sections. It never generates signals, evaluates thresholds,
    interprets AnalysisResult objects or makes trading decisions.
    """

    def create_sections(self, signal_result: SignalResult) -> list[GuiSection]:
        sections = [
            self._create_summary_section(signal_result),
            self._create_score_section(signal_result),
        ]

        notes = self._create_notes_section(signal_result)
        if notes is not None:
            sections.append(notes)

        return sections

    def _create_summary_section(self, signal_result: SignalResult) -> GuiSection:
        return GuiSection(
            title="Signal Dashboard",
            description="High-level deterministic output from the Signal Layer.",
            metrics=[
                GuiMetric("Symbol", signal_result.symbol.upper() or "N/A"),
                GuiMetric("Signal", signal_result.signal.value),
                GuiMetric("Confidence", str(signal_result.confidence)),
            ],
        )

    def _create_score_section(self, signal_result: SignalResult) -> GuiSection:
        return GuiSection(
            title="Signal Scores",
            description="Signal scores calculated before the GUI receives the result.",
            metrics=[
                GuiMetric("Bullish Score", str(signal_result.bullish_score)),
                GuiMetric("Bearish Score", str(signal_result.bearish_score)),
                GuiMetric("Neutral Score", str(signal_result.neutral_score)),
            ],
        )

    def _create_notes_section(self, signal_result: SignalResult) -> GuiSection | None:
        if not signal_result.notes:
            return None

        return GuiSection(
            title="Signal Notes",
            description="Deterministic notes generated by the Signal Layer.",
            metrics=[
                GuiMetric(f"Note {index}", note)
                for index, note in enumerate(signal_result.notes, start=1)
            ],
        )
