from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
from enum import Enum


class TradeStatus(str, Enum):
    """
    Current lifecycle state of a trade.
    """

    PENDING = "PENDING"
    OPEN = "OPEN"
    CLOSED = "CLOSED"


class ExitSignal(str, Enum):
    """
    Deterministic exit decision generated by Orion.
    """

    HOLD_POSITION = "HOLD_POSITION"
    TAKE_PROFIT = "TAKE_PROFIT"
    STOP_LOSS = "STOP_LOSS"
    TRAILING_STOP = "TRAILING_STOP"
    EXIT_DUE_TO_WEAKNESS = "EXIT_DUE_TO_WEAKNESS"
    EXIT_DUE_TO_TIME_LIMIT = "EXIT_DUE_TO_TIME_LIMIT"


@dataclass(frozen=True)
class Trade:
    """
    Central trade domain model.

    The Trade itself contains no business logic.
    It stores deterministic lifecycle and RiskPlan data.
    """

    # ---------- Identity ----------

    symbol: str

    # ---------- Entry ----------

    quantity: int

    entry_price: float

    entry_datetime: datetime

    entry_reason: str

    confidence: float

    # ---------- Current market ----------

    current_price: float

    highest_price: float

    lowest_price: float

    # ---------- RiskPlan ----------

    stop_loss: float

    take_profit: float

    target_1: float = 0.0

    target_2: float = 0.0

    target_3: float = 0.0

    risk_percent: float = 0.0

    reward_percent: float = 0.0

    risk_reward_ratio: float = 0.0

    risk_plan_confidence: float = 0.0

    risk_plan_notes: str = ""

    trailing_stop: float | None = None

    # ---------- Status ----------

    status: TradeStatus = TradeStatus.OPEN

    exit_signal: ExitSignal = ExitSignal.HOLD_POSITION

    exit_reason: str = ""

    # ---------- Exit ----------

    exit_price: float | None = None

    exit_datetime: datetime | None = None

    # ---------- Performance ----------

    realized_profit_loss: float = 0.0

    unrealized_profit_loss: float = 0.0

    unrealized_profit_loss_percent: float = 0.0

    # ---------- Metadata ----------

    notes: str = ""